app/blueprints/auth.py
from flask import Blueprint, request, redirect, render_template, url_for, flash, session, jsonify
from flask_login import login_user,logout_user, login_required, current_user
import smtplib
from datetime import timedelta
import random
from app import db
from app.models import User, Appointment
from passlib.hash import bcrypt
from email.message import EmailMessage
from email.mime.text import MIMEText

auth = Blueprint('auth', __name__)


def Appointment_mail(name, email, phone, gender, appType, appDate, message):

    username = 'bhattshubham247@gmail.com'
    password = 'tbjibaqtwregxvwn'

    SUBJECT = "Appointment Booked!"
    FROM = username
    TO = email
    TEXT = f'Dear {name}, \nYou have Booked an Appointment on our website. We will try to call you soon regarding your appointment and give you the timings.\n\nKindly, Do not reply on this mail.\n\nBest Regards,\nHMS Director'
    OWNER_TEXT = f'Dear Sir,\nPatient Name - {name}\nPatient Email - {email}\nPhone - {phone}\nGender - {gender}\nAppoint For - {appType}\nAppointment Date - {appDate}\nPatient Message - {message}\n\n Please Inform to {name} and give all the updates!\n\nRegards,\nBot HMS ORG'

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(username, password)
    
    msg = EmailMessage()
    msg['Subject'] = SUBJECT
    msg['From'] = FROM
    msg['To'] = TO
    msg.set_content(TEXT)
    server.send_message(msg)


    msg = EmailMessage()
    msg['Subject'] = SUBJECT
    msg['From'] = TO
    msg['To'] = FROM
    msg.set_content(OWNER_TEXT)
    server.send_message(msg)
   
    server.quit()

def New_register(name, user_name, email):

    username = 'bhattshubham247@gmail.com'
    password = 'tbjibaqtwregxvwn'

    SUBJECT = f"ACCOUNT REGISTERED! | {user_name} | HMS ORG"
    FROM = username
    TO = email
    TEXT = f'Dear {name}, \nYou have registeres your account by this Username -> [{user_name}].\n\nKindly, Verify you account by clicking on the given link: http://127.0.0.1:5000/auth/login \n\nBest Regards,\nHMS Director'

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(username, password)
    
    # TO USER
    msg = EmailMessage()
    msg['Subject'] = SUBJECT
    msg['From'] = FROM
    msg['To'] = TO
    msg.set_content(TEXT)
    server.send_message(msg)
    server.quit()


@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST', 'GET'])
def login_post():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()

        if user and bcrypt.verify(password, user.password):
            login_user(user)  # Log in the user
            session.permanent = True
            session['email'] = email
            return redirect(url_for('main.index'))
    
    flash('Invalid username or password')
    return redirect(url_for('auth.login'))

@auth.route('/profile')
def profile():
    if 'email' in session:
        return render_template('profile.html', name = current_user.name, profession = current_user.profession, bio = current_user.bio)
    else:
        return redirect(url_for('auth.login'))
    
@auth.route('/appointment')
@login_required
def book_an_appointment():
    return render_template('appointment.html')

@auth.route('/appointment', methods=['POST', 'GET'])
@login_required
def book_an_appointment_post():
     if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        phone = request.form.get('phone')
        gender = request.form.get('gender')
        appointmentType = request.form.get('appointmentType')
        other = request.form.get('other')
        booking_date = request.form.get('booking_date')
        message = request.form.get('message')

        print(name, email, booking_date, message)

        new_appointment = Appointment(name=name, email=email, phone=phone, gender=gender, appointmentType=appointmentType, other=other, booking_date = booking_date, message = message)

        db.session.add(new_appointment)
        db.session.commit()
        db.session.close()

        Appointment_mail(name, email, phone, gender, appointmentType, booking_date, message)

        return redirect(url_for('main.index'))

        # return render_template('appointment.html')  

@auth.route('/signup')
def register():
    return render_template('register.html')


@auth.route('/signup', methods=['POST', 'GET'])
def register_post():
    if request.method == 'POST':
        name = request.form.get('name')
        username = request.form.get('username') 
        email = request.form.get('email')
        password = request.form.get('password')
        hashed_pass = bcrypt.hash(password)

        user_email = User.query.filter_by(email=email).first()
        user_name = User.query.filter_by(username=username).first()
        if user_email and user_name:
            flash('This User already exists')
            return redirect(url_for('auth.register'))
        
        elif name == '' or email == '' or username == '' or password == '':
            flash('Fill all the Credentials')
            return redirect(url_for('auth.register'))
        
        else:
            new_user = User(username=username, name=name, email=email, password=hashed_pass)

            db.session.add(new_user)
            db.session.commit()
            db.session.close()

            New_register(name, username, email)

    return redirect(url_for('auth.login')) 


@auth.route('/forgotPassword')
def forgotPassword():
    return render_template('forget_password.html')

@auth.route('/forgotPassword', methods=['POST', 'GET'])
def forgot_password_post():
    if request.method == 'POST':
        forgData = request.json
        email = forgData['email']
        user = User.query.filter_by(email=email).first()
        if not user:
            return redirect(url_for('auth.login'))

        else:    
            # update the user's password
            # msg = forgotten_mail(user.name, user.email)
            # print(msg)
            user.password = bcrypt.hash(forgData['password'])
            db.session.commit()
            db.session.close()
        
        return redirect(url_for('auth.login'))
   
    return redirect(url_for('auth.forgot_password'))

@auth.route('/passwordUpdated')
def passwordUpdated():
    return render_template('passwordUpdated.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()  # Log out the user
    db.session.close()
    session.clear()
    return redirect(url_for('auth.login'))

app/blueprints/main.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import login_required, current_user, login_remembered
from email.message import EmailMessage
import smtplib
from app.models import User, Contact_Us
from app import db

main = Blueprint('main', __name__) 

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about_Sec():
    return render_template('about.html')

@main.route('/contact')
def contact():
    return render_template('contact.html')

@main.route('/get_in_touch', methods=['POST', 'GET'])
def get_in_touch():
        if request.method == 'POST':
            name = request.form.get('name')
            email = request.form.get('email')
            message = request.form.get('message')

            contact_upt = Contact_Us(name=name, email=email, message=message)

            db.session.add(contact_upt)
            db.session.commit()
            db.session.close()

        return redirect(url_for('main.index')) 

def get_in_touch(name, email, message):

    username = 'bhattshubham247@gmail.com'
    password = 'tbjibaqtwregxvwn'

    SUBJECT = "Get in Touch :)"
    FROM = username
    TO = email
    TEXT_USER = f'Dear {name}, \nThank you for indulging with us. We will try to resolve your query and let you know as soon as possible.\n\nKindly, Do not Reply on this mail.\n\nBest Regards,\nShubham Bhatt'
    TEXT_OWNER = f"Dear Sir, \n{name} has sent you a mail. he is getting some query. here is the query of {name}\n\n{name}'s Query -> {message}.\n\nKindly, Reply him/her as soon as possible.\n\nRegards,\nBot HMS"
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(username, password)
    
    # To User
    msg = EmailMessage()
    msg['Subject'] = SUBJECT
    msg['From'] = FROM
    msg['To'] = TO
    msg.set_content(TEXT_USER)
    server.send_message(msg)

    # To Owner
    msg = EmailMessage()
    msg['Subject'] = SUBJECT
    msg['From'] = TO
    msg['To'] = FROM
    msg.set_content(TEXT_OWNER)
    server.send_message(msg)

    server.quit()

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{ url_for('static', filename=('css/main.css')) }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <style>
        .material-symbols-outlined {
            width: 2rem;
            height: 2rem;
          font-variation-settings:
          'FILL' 0,
          'wght' 400,
          'GRAD' 0,
          'opsz' 48
        }
        </style>
    {% block content %}{% endblock %}

</body>
</html>

app/templates/footer.html
{% extends 'base.html' %}
{% block content %}

    <!-- component -->
<div class="flex items-end w-full bg-white">

    <footer class="w-full text-gray-700 bg-gray-900 body-font">
        <div
            class="container flex flex-col flex-wrap px-5 py-24 mx-auto md:items-center lg:items-start md:flex-row md:flex-no-wrap">
            <div class="flex-shrink-0 w-64 mx-auto text-center md:mx-0 md:text-left">
                
                <h1 class="font-poppins font-semibold text-gray-100">
                    <a href="{{ url_for('main.index') }}"><img class="h-14 w-35 rounded-lg" src="../static/resources/logo.png" alt="logo"></a>
                </h1>

                <p class="mt-2 text-sm text-gray-500">Design, Code and Ship!</p>
                <div class="mt-4">
                    <span class="inline-flex justify-center mt-2 sm:ml-auto sm:mt-0 sm:justify-start">
                        <a href="https:\\www.facebook.com" target="_blank" class="cursor-pointer hover:text-gray-200">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                class="w-5 h-5" viewBox="0 0 24 24">
                                <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                            </svg>
                        </a>
                        <a href="https:\\www.twitter.com" target="_blank" class="ml-3 text-gray-500 cursor-pointer hover:text-gray-200">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                class="w-5 h-5" viewBox="0 0 24 24">
                                <path
                                    d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                                </path>
                            </svg>
                        </a>
                        <a href="https://www.instagram.com/" target="_blank" class="ml-3 text-gray-500 cursor-pointer hover:text-gray-200">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                                <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                            </svg>
                        </a>
                        <a href="https:\\www.linkedin.com" target="_blank" class="ml-3 text-gray-500 cursor-pointer hover:text-gray-200">
                            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                                <path stroke="none"
                                    d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z">
                                </path>
                                <circle cx="4" cy="4" r="2" stroke="none"></circle>
                            </svg>
                        </a>
                    </span>
                </div>
            </div>
            <div class="flex flex-wrap flex-grow mt-10 -mb-10 text-center md:pl-20 md:mt-0 md:text-left">
                <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                    <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-100 uppercase title-font">About</h2>
                    <nav class="mb-10 list-none">
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Company</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Careers</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Blog</a>
                        </li>
                    </nav>
                </div>
                <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                    <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-100 uppercase title-font">Support</h2>
                    <nav class="mb-10 list-none">
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Contact Support</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Help Resources</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Release Updates</a>
                        </li>
                    </nav>
                </div>
                <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                    <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-100 uppercase title-font">Platform
                    </h2>
                    <nav class="mb-10 list-none">
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Terms &amp; Privacy</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Pricing</a>
                        </li>
                        <li class="mt-3">
                            <a href="http://127.0.0.1:5000/about#faqs" class="text-gray-500 cursor-pointer hover:text-gray-200">FAQ</a>
                        </li>
                    </nav>
                </div>
                <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                    <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-100 uppercase title-font">Contact</h2>
                    <nav class="mb-10 list-none">
                        <li class="mt-3">
                            <a href="{{ url_for('main.contact') }}" class="text-gray-500 cursor-pointer hover:text-gray-200">Send a Message</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">Request a Quote</a>
                        </li>
                        <li class="mt-3">
                            <a class="text-gray-500 cursor-pointer hover:text-gray-200">+91- 9310852719</a>
                        </li>
                    </nav>
                </div>
            </div>
        </div>
        <div class="bg-gray-900">
            <div class="container px-5 py-4 mx-auto">
                <p class="text-sm text-gray-500 capitalize xl:text-center">© 2020 All rights reserved </p>
            </div>
        </div>
    </footer>

</div>


{% endblock %}

app/templates/hero.html
{% extends 'base.html' %}
{% block content %}

<!-- component -->
<style>
    .bg-dots{
      background-image: url(https://assets-global.website-files.com/5b5a66e9f3166b36708705fa/5dea7a12bb83ab1f13040de5_cx-dots.svg);
      background-repeat: no-repeat
    }
  </style>
  
  <div id="hero" class="m-auto max-w-6xl p-12">
     <div class="flex flex-col md:flex-row">
        <div class="md:w-1/2 flex flex-col justify-center">
           <div class="md:text-5xl text-2xl uppercase font-black">Your gateway to healthcare excellence</div>
           <div class="text-xl mt-4">Welcome to MediNET, your one-stop destination for seamless healthcare services and medical supplies.</div>
           <a href="{{ url_for('auth.book_an_appointment') }}">
              <div class="my-5 h-16">
                 <div class="shadow-md font-medium py-2 px-4 text-yellow-100
                    cursor-pointer bg-yellow-600 hover:bg-yellow-500 rounded text-lg text-center w-48">Book Now!</div>
              </div>
           </a>
        </div>
        <div class="flex md:justify-end w-full md:w-1/2 -mt-5">
           <div class="bg-dots">
              <div class="shadow-2xl max-w-md z-10 rounded-full mt-6 ml-4">
                 <img alt="card img" class="rounded-t" src="https://plus.unsplash.com/premium_photo-1661507010373-85c3507f8c65?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"> 
                 <div class="text-2xl p-10 bg-[#ca8a04] text-white font-semibold text-left">
                    <!-- <img alt="quote" class="float-left mr-1" src="https://assets-global.website-files.com/5b5a66e9f3166b36708705fa/5cf8fb1f994fb7168d0d66fb_quote-intro.svg">  -->
                    <svg viewBox="0 0 24 24" fill="none" class="w-8" xmlns="http://www.w3.org/2000/svg" stroke="#FFFFFF"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M8.09 11.6314H3.4C3.48 6.96144 4.4 6.19144 7.27 4.49144C7.6 4.29144 7.71 3.87144 7.51 3.53144C7.32 3.20144 6.89 3.09144 6.56 3.29144C3.18 5.29144 2 6.51144 2 12.3214V17.7114C2 19.4214 3.39 20.8014 5.09 20.8014H8.09C9.85 20.8014 11.18 19.4714 11.18 17.7114V14.7114C11.18 12.9614 9.85 11.6314 8.09 11.6314Z" fill="#FFFFFF"></path> <path d="M18.9086 11.6314H14.2186C14.2986 6.96144 15.2186 6.19144 18.0886 4.49144C18.4186 4.29144 18.5286 3.87144 18.3286 3.53144C18.1286 3.20144 17.7086 3.09144 17.3686 3.29144C13.9886 5.29144 12.8086 6.51144 12.8086 12.3314V17.7214C12.8086 19.4314 14.1986 20.8114 15.8986 20.8114H18.8986C20.6586 20.8114 21.9886 19.4814 21.9886 17.7214V14.7214C21.9986 12.9614 20.6686 11.6314 18.9086 11.6314Z" fill="#FFFFFF"></path> </g></svg>
                    Discover the future of healthcare with MediNET. Book appointments, purchase medicines, and access advanced medical tools all in one place.  
                  </div>
              </div>
           </div>
        </div>
     </div>
  </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    {% include 'header.html' %}
    {% include 'hero.html' %}
    {% include 'services.html' %}

    <div class="fixed bottom-0 right-0 mb-4 mr-4 z-10">
        <div>
          <a
            title="Follow me on twitter"
            href="#"
            class="block w-16 h-16 rounded-full transition-all shadow hover:shadow-lg transform hover:scale-110"
          >
            <img
              class="object-cover object-center w-full h-full rounded-full bg-[#EA8A04]"
              src="https://img.icons8.com/?size=512&id=39805&format=png"
            />
          </a>
        </div>
      </div>
      
    {% include 'product_section.html' %}
    {% include 'testimonials.html' %}
    {% include 'footer.html' %}
{% endblock %}
```

app/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

{% include 'header.html' %}

<!-- component -->
<!-- Container -->
<div class="flex flex-wrap min-h-screen w-full content-center justify-center bg-gray-200 py-10">
  
    <!-- Login component -->
    <div class="flex shadow-md">
      <!-- Login form -->
      <div class="flex flex-wrap content-center justify-center rounded-l-md bg-white" style="width: 24rem; height: 32rem;">
        <div class="w-72">
          <!-- Heading -->
          <h1 class="text-xl font-semibold">Welcome back</h1>
          <small class="text-gray-400">Welcome back! Please enter your details</small>
  
          <!-- Form -->
          <form class="mt-4" method="POST">
            <div class="mb-3">
              <label class="mb-2 block text-xs font-semibold">Email</label>
              <input type="email" name="email" placeholder="Enter your email" class="block w-full rounded-md border border-gray-300 focus:border-purple-700 focus:outline-none focus:ring-1 focus:ring-purple-700 py-1 px-1.5 text-gray-500" />
            </div>
  
            <div class="mb-3">
              <label class="mb-2 block text-xs font-semibold">Password</label>
              <input type="password" name="password" placeholder="*****" class="block w-full rounded-md border border-gray-300 focus:border-purple-700 focus:outline-none focus:ring-1 focus:ring-purple-700 py-1 px-1.5 text-gray-500" />
            </div>
  
            <div class="mb-3 flex flex-wrap content-center">
              <input id="remember" type="checkbox" class="mr-1 checked:bg-purple-700" /> <label for="remember" class="mr-auto text-xs font-semibold">Remember for 30 days</label>
              <a href="{{ url_for('auth.forgotPassword') }}" class="text-xs font-semibold text-purple-700">Forgot password?</a>
            </div>
  
            <div class="mb-3">
              <button class="mb-1.5 block w-full text-center text-white bg-purple-700 hover:bg-purple-900 px-2 py-1.5 rounded-md">Sign in</button>
            </div>
          </form>
  
          <!-- Footer -->
          <div class="text-center">
            <span class="text-xs text-gray-400 font-semibold">Don't have account?</span>
            <a href="{{ url_for('auth.register') }}" class="text-xs font-semibold text-purple-700">Sign up</a>
          </div>
        </div>
      </div>
  
      <!-- Login banner -->
      <div class="flex flex-wrap content-center justify-center rounded-r-md" style="width: 24rem; height: 32rem;">
        <img class="w-full h-full bg-center bg-no-repeat bg-cover rounded-r-md" src="https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80">
      </div
  
    </div>
  

{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}

{% include 'header.html' %}

<!-- component -->
<div class="m-10 md:flex">
	<div
		class="rounded-3xl relative overflow-hidden md:flex w-1/2 bg-gradient-to-tr from-blue-800 to-purple-700 i justify-around items-center hidden">
		<div>
			<h1 class="text-white font-bold text-4xl font-sans">HOSPITAL MIS</h1>
			<p class="text-white mt-1">If you have Alreadyand account so click on Login</p>
			<a href="{{ url_for('auth.login') }}"><button type="submit" class="block w-28 bg-white text-indigo-800 mt-4 py-2 rounded-2xl font-bold mb-2">Login Now!</button></a>
		</div>
		<div class="absolute -bottom-32 -left-40 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -bottom-40 -left-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-40 -right-0 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-20 -right-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
	</div>
	<div class="flex md:w-1/2 justify-center py-10 items-center bg-white">
		<form class="bg-white" method="POST">
			<h1 class="text-gray-800 font-bold text-2xl mb-1">Register Yourself!</h1>
			<p class="text-sm font-normal text-gray-600 mb-7">Welcome to HMS</p>
			<div class="flex items-center border-2 py-2 px-3 rounded-2xl mb-4">
				<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20"
					fill="currentColor">
					<path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
						clip-rule="evenodd" />
				</svg>
				<input class="pl-2 outline-none border-none" type="text" name="name" id="name" placeholder="Full name" />
      </div>
				<div class="flex items-center border-2 py-2 px-3 rounded-2xl mb-4">
					<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" fill="none"
						viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
							d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-3.44-2.04l.054-.09A13.916 13.916 0 008 11a4 4 0 118 0c0 1.017-.07 2.019-.203 3m-2.118 6.844A21.88 21.88 0 0015.171 17m3.839 1.132c.645-2.266.99-4.659.99-7.132A8 8 0 008 4.07M3 15.364c.64-1.319 1-2.8 1-4.364 0-1.457.39-2.823 1.07-4" />
					</svg>
					<input class="pl-2 outline-none border-none" type="text" name="username" id="username" placeholder="Username" />
      </div>
					<div class="flex items-center border-2 py-2 px-3 rounded-2xl mb-4">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" fill="none"
							viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
								d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
						</svg>
						<input class="pl-2 outline-none border-none" type="email" name="email" id="email" placeholder="Email Address" />
      </div>
						<div class="flex items-center border-2 py-2 px-3 rounded-2xl">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20"
								fill="currentColor">
								<path fill-rule="evenodd"
									d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
									clip-rule="evenodd" />
							</svg>
							<input class="pl-2 outline-none border-none" type="password" name="password" id="password" placeholder="Password" />
      </div>
							<button type="submit" class="block w-full bg-indigo-600 mt-4 py-2 rounded-2xl text-white font-semibold mb-2">Register Now!</button>
							<a href="{{ url_for('auth.forgotPassword') }}"><span class="text-sm ml-2 hover:text-blue-500 cursor-pointer">Forgot Password ?</span></a>
		</form>
	</div>
</div>

{% include 'footer.html' %}
{% endblock %}